cargo-features = ["edition2021"]

[package]
name = "token-solana-rust"
version = "0.1.0"
edition = "2021"


[dependencies]
borsh = "0.9"
solana-program = "=1.10.9"
thiserror = "1.0"

[lib]
crate-type = ["cdylib", "lib"]